services:
  web:
    image: "infracloudio/csvserver:latest"
    volumes:
      - /root/Infracloud/InfraCloudTest/solution/inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    env_file: csvserver.env
  prom:
    image: "prom/prometheus:v2.22.0"
    ports:
      - "9090:9090"
    volumes:
      - /root/Infracloud/InfraCloudTest/solution/prometheus.yml:/etc/prometheus/prometheus.yml 
