services:
  web:
    image: "infracloudio/csvserver:latest"
    volumes:
      - /root/Infracloud/InfraCloudTest/solution/inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    env_file: csvserver.env
